# Generated by Django 2.0.1 on 2018-04-03 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(default=10)),
                ('identifier', models.CharField(default=uuid.UUID('8b71073b-c3c5-47f4-9b7a-e6fa647d02fb'), max_length=64, unique=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_data', to='cms.Content')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.IntegerField(choices=[(0, 'All'), (3, 'Create'), (2, 'Edit'), (4, 'NoAccess'), (1, 'View')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('uuid', models.UUIDField(default=uuid.UUID('f2ddaa27-76b4-4593-8362-bf2af9853161'), unique=True)),
                ('auth', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_main_menu', models.BooleanField(default=True)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('dropdown_items', models.ManyToManyField(blank=True, related_name='_menugroup_dropdown_items_+', to='cms.MenuGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('path', models.CharField(default=uuid.UUID('327dc9fc-6d62-45e3-aba9-b544ddf7ce52'), max_length=64, unique=True)),
                ('contents', models.ManyToManyField(to='cms.Content')),
            ],
        ),
        migrations.AddField(
            model_name='menugroup',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='menugroup',
            name='submenus',
            field=models.ManyToManyField(blank=True, related_name='_menugroup_submenus_+', to='cms.MenuGroup'),
        ),
        migrations.AddField(
            model_name='menuaccesscontrol',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuGroup'),
        ),
    ]
