# Generated by Django 2.0.1 on 2018-04-10 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.CharField(default=uuid.UUID('24e140e3-5ece-4fc3-8597-4d241ae323fc'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c19915c1-be14-4df7-8f40-1648849bb38c'), unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(default=uuid.UUID('44aa7633-e429-4897-b457-4cd0e058ede4'), max_length=64, unique=True),
        ),
    ]
