# Generated by Django 2.0.1 on 2018-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='browser_title',
            field=models.CharField(blank=True, default='MiNi CMS', max_length=256),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='hide_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='app_name',
            field=models.CharField(blank=True, default='MiNi CMS', max_length=32),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='footer',
            field=models.TextField(blank=True, null=True, verbose_name='App Footer'),
        ),
    ]
