# Generated by Django 2.0.1 on 2018-04-11 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180411_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c0633743-ac05-431f-a6b8-eed3828eb2b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
