# Generated by Django 2.0.1 on 2018-04-12 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180411_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdata',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Content Body'),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f97e4fe1-3edf-4c50-bb3d-6bddfa309fb7'), unique=True),
        ),
        migrations.DeleteModel(
            name='ContentData',
        ),
    ]
