# Generated by Django 2.0.1 on 2018-04-26 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180412_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c196eba8-2910-46d2-885d-e51de8a5bd39'), unique=True),
        ),
    ]
