# Generated by Django 2.0.1 on 2018-04-27 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20180427_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(default='MiNi CMS', max_length=32)),
                ('footer', models.TextField(verbose_name='App Footer')),
            ],
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2a17eb96-13b6-4b54-b5a8-e08058d93827'), unique=True),
        ),
    ]
