# Generated by Django 2.0.1 on 2018-04-27 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20180427_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='footer',
            field=models.TextField(null=True, verbose_name='App Footer'),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b1ea9163-6afc-4cff-b0e2-ce1b6240070e'), unique=True),
        ),
    ]
