# Generated by Django 2.0.1 on 2018-04-30 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20180427_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5d2364ce-1e66-4fdf-9a95-16b91e9741c3'), unique=True),
        ),
    ]
