# Generated by Django 2.0.1 on 2018-04-30 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20180430_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e53d7b09-c751-4591-af24-cad46fbcf202'), unique=True),
        ),
    ]
