# Generated by Django 2.0.1 on 2018-04-30 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20180430_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6adf8e79-6c06-49d5-bdef-5a9d55b2d7e5'), unique=True),
        ),
    ]
