# Generated by Django 2.0.1 on 2018-04-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20180430_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
