# Generated by Django 2.0.1 on 2018-05-02 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.TextField(verbose_name='Comment or Reply')),
                ('status', models.IntegerField(default=0)),
                ('replies', models.ManyToManyField(related_name='_comment_replies_+', to='discuss.Comment')),
            ],
        ),
    ]
