# Generated by Django 2.0.1 on 2018-04-30 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ece213ea-ad96-4296-88e8-324a1624e2d5'), editable=False),
        ),
    ]
