# Generated by Django 2.0.1 on 2018-04-30 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0004_auto_20180430_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cca6fa44-a6a9-4a78-9cae-86ef767c2e5f'), editable=False),
        ),
    ]
