# Generated by Django 2.0.1 on 2018-05-02 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(default='MiNi CMS', max_length=32)),
                ('footer', models.TextField(null=True, verbose_name='App Footer')),
            ],
        ),
        migrations.CreateModel(
            name='AppLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(default=0)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True, null=True, verbose_name='Content Body')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.IntegerField(choices=[(0, 'All'), (3, 'Create'), (2, 'Edit'), (4, 'NoAccess'), (1, 'View')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('auth', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_main_menu', models.BooleanField(default=True)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('dropdown_items', models.ManyToManyField(blank=True, related_name='_menugroup_dropdown_items_+', to='cms.MenuGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=32)),
                ('path', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('contents', models.ManyToManyField(to='cms.Content')),
            ],
        ),
        migrations.AddField(
            model_name='menugroup',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
        migrations.AddField(
            model_name='menugroup',
            name='submenus',
            field=models.ManyToManyField(blank=True, related_name='_menugroup_submenus_+', to='cms.MenuGroup'),
        ),
        migrations.AddField(
            model_name='menuaccesscontrol',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuGroup'),
        ),
    ]
