# Generated by Django 2.0.1 on 2018-02-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='static/media/')),
            ],
        ),
    ]
