# Generated by Django 2.0.1 on 2018-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_config', '0002_applogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menugroup',
            name='identifier',
            field=models.CharField(max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applogo',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='path',
            field=models.CharField(max_length=64),
        ),
    ]
